version: 2
jobs:
  deploy:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:0b:32:7a:d0:1d:80:ca:2a:cd:50:6d:be:30:b8:10"
            -
      - run:
          name: Fetch Changes
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd backend; git reset --hard; git pull --rebase;'
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'cd backend; ./devops/deploy.sh;'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
